#app:
#  id: marketing-service
#  env: dev
#
#apollo:
#  meta:
#    dev: *
#  autoUpdateInjectedSpringProperties: true
#  bootstrap:
#    namespaces: application
#    eagerLoad:
#      enabled: true
#    enabled: true



#spring:
#  application:
#    name: marketing-service
#  profiles:
#    active: dev
#  cloud:
#    apollo:
#      config:
#        server-addr: *
#        namespaces:
#          -
#            name: application
#            refreshable: true
#          -
#            name: pre
#            refreshable: true
#      refreshable: true
